# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind '"' split-window -c "#{pane_current_path}"
bind '%' split-window -h -c "#{pane_current_path}"
bind r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"

# Start numbering panes and windows from 1
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# Status bar: oane title and sessio nname on  the right, no datetime
set -g status-right-length 80
set -g status-right "#{session_name} "
set -g status-left-length 0
set -g status-left ""
